version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysqltest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8081:80

    web:
        build: ./docker/php/web/
        container_name: php
        depends_on:
            - db
        volumes:
            - ./www/lumen/:/var/www/html
            - ./docker/php/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - "8080:80"
        stdin_open: true
        tty: true
        environment:
            DB_HOST: db
            DB_NAME: database
            DB_PASSWORD: root

    cli:
        build: ./docker/php/cli/
        container_name: php_cli
        volumes:
            - ./www/lumen/:/var/www/html
        stdin_open: true
        tty: true
        environment:
            DB_HOST: db
            DB_PASSWORD: root
            DB_NAME: database

volumes:
    db-data:
